---
config:
  imagesPath: "./img/characters/"
characters:
  game:
    name: ''
    color: white
  player:
    sprites:
      idle:
        image: Oliver.webp
        width: 256
        height: 256
    style:
      color: "#7f06e2"
      textCss:
        color: white
        font-family: Comic Sans MS
    name: Oliver
  assistant:
    sprites:
      idle: 
        image: Assistant.webp
        width: 256
        height: 256
    style:
      color: white
    name: Assistant
  assistentMerti:
    sprites:
      idle: 
        image: AssistentMerti.webp
        width: 256
        height: 256
    style:
      color: white
    name: Assistent Merti
  malinka:
    sprites:
      idle: 
        image: Malinka.webp
        width: 256
        height: 256
    style:
      color: pink
    name: Malinka
  adelina:
    sprites:
      idle: 
        image: Adelind.webp
        width: 256
        height: 256
    style:
      color: white
    name: Adelaida
  mama:
    sprites:
      idle: 
        image: Mama.webp
        width: 256
        height: 256
    style:
      color: white
    name: Mama
  din:
    sprites:
      idle: 
        image: Din.webp
        width: 256
        height: 256
    style:
      color: white
    name: Din

  

