---
config:
  imagesPath: "./img/characters/"
characters:
  game:
    name: ''
    color: white
  player:
    sprites:
      idle:
        image: oliver.webp
        width: 256
        height: 256
    style:
      color: "#7f06e2"
      textCss:
        color: white
        font-family: Comic Sans MS
    name: Oliver
  assistant:
    sprites:
      idle: 
        image: assistant.webp
        width: 256
        height: 256
    style:
      color: white
    name: Assistant
  assistant_updated:
    sprites:
      idle: 
        image: assistant_updated.webp
        width: 256
        height: 256
    style:
      color: white
    name: Assistant
  malinka:
    sprites:
      idle: 
        image: malinka.webp
        width: 256
        height: 256
    style:
      color: pink
    name: Malinka
  adelina:
    sprites:
      idle: 
        image: adelina.webp
        width: 256
        height: 256
    style:
      color: white
    name: Adelaida
  mother:
    sprites:
      idle: 
        image: mother.webp
        width: 256
        height: 256
    style:
      color: white
    name: Mama

