---
config:
  imagesPath: "./img/characters/"
characters:
  game:
    name: ''
    color: white
  player:
    sprites:
      idle:
        image: oliver.webp
        width: 256
        height: 256
    style:
      color: "#7f06e2"
      textCss:
        color: white
        font-family: Comic Sans MS
    name: Oliver
  assistant:
    sprites:
      idle: 
        image: assistant.webp
        width: 256
        height: 256
    style:
      color: white
    name: Assistant
  assistant_updated:
    sprites:
      idle: 
        image: assistant_updated.webp
        width: 256
        height: 256
    style:
      color: white
    name: Assistant
  malinki:
    sprites:
      idle: 
        image: malinki.webp
        width: 256
        height: 256
    style:
      color: white
    name: Malinki


